// src/levels.js

export const levels = [
  {
    id: 1,
    title: "Seviye 1: İlk Kod Adımı (Girdi & Çıktı)",
    goal: "Girdi alanındaki sayıyı doğrudan çıktı alanına aktar.",
    inputData: [8],
    expectedOutput: [8],
    initialBlocks: [
      { id: "mult2", function: "Çarp x2", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox", function: "GİRDİ AL", type: "io" },
    ],
    correctOrder: ["inbox", "outbox"],
  },
  {
    id: 2,
    title: "Seviye 2: Sayıyı İkiyle Çarp",
    goal: "Girdi alanındaki sayıyı al, 2 ile çarp ve çıktıya teslim et.",
    inputData: [6],
    expectedOutput: [12],
    initialBlocks: [
      { id: "mult2", function: "Çarp x2", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox", function: "GİRDİ AL", type: "io" },
    ],
    correctOrder: ["inbox", "mult2", "outbox"],
  },
  {
    id: 3,
    title: "Seviye 3: İki Sayıyı Topla",
    goal: "Gelen iki sayıyı sırayla al, topla ve sonucu çıktıya ver.",
    inputData: [4, 9],
    expectedOutput: [13],
    initialBlocks: [
      { id: "add", function: "TOPLA (A + B)", type: "action" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: ["inbox_1", "inbox_2", "add", "outbox"],
  },
  {
    id: 4,
    title: "Seviye 4: Sadece Pozitif Sayıları Geçir",
    goal: "Sayıyı al. Eğer sayı 0'dan büyükse çıktıya ver, 0 ise işlemi bitir.",
    inputData: [5],
    expectedOutput: [5],
    initialBlocks: [
      { id: "mult2", function: "Çarp x2", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "check_zero", function: "EĞER SIFIRSA BİTİR", type: "logic" },
      { id: "inbox", function: "GİRDİ AL", type: "io" },
    ],
    correctOrder: ["inbox", "check_zero", "outbox"],
  },
  {
    id: 5,
    title: "Seviye 5: Mutlak Değer Hesabı",
    goal: "Gelen sayı negatifse pozitife çevir (x -1), pozitifse olduğu gibi çıktıya ver.",
    inputData: [-7],
    expectedOutput: [7],
    initialBlocks: [
      {
        id: "negate",
        function: "EĞER NEGATİFSE SIGNO Değiştir (x -1)",
        type: "action",
      },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox", function: "GİRDİ AL", type: "io" },
    ],
    correctOrder: ["inbox", "negate", "outbox"],
  },
  {
    id: 6,
    title: "Seviye 6: İki Sayının Farkını Bul",
    goal: "Sırayla 1. ve 2. sayıyı al, (2. Sayı - 1. Sayı) işlemini yapıp çıktıya ver.",
    inputData: [3, 10],
    expectedOutput: [7],
    initialBlocks: [
      { id: "square", function: "KARESİNİ AL (A²)", type: "action" },
      { id: "sub", function: "ÇIKAR (B - A)", type: "action" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: ["inbox_1", "inbox_2", "sub", "outbox"],
  },
  {
    id: 7,
    title: "Seviye 7: Çift Sayı Filtresi",
    goal: "Gelen sayının 2'ye bölümünden kalana bak. Çift ise çıktıya ver, tek ise es geç.",
    inputData: [8],
    expectedOutput: [8],
    initialBlocks: [
      { id: "check_even", function: "EĞER TEKSE BİTİR", type: "logic" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox", function: "GİRDİ AL", type: "io" },
    ],
    correctOrder: ["inbox", "check_even", "outbox"],
  },
  {
    id: 8,
    title: "Seviye 8: Sayının Karesini Al",
    goal: "Girdi sayısını al, kendisiyle çarp (A x A) ve sonucu çıktıya gönder.",
    inputData: [4],
    expectedOutput: [16],
    initialBlocks: [
      { id: "square", function: "KARESİNİ AL (A²)", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox", function: "GİRDİ AL", type: "io" },
    ],
    correctOrder: ["inbox", "square", "outbox"],
  },
  {
    id: 9,
    title: "Seviye 9: Büyük Olan Sayıyı Bul (MAX)",
    goal: "Gelen iki sayıyı kıyasla, sadece büyük olanı çıktı alanına gönder.",
    inputData: [12, 25],
    expectedOutput: [25],
    initialBlocks: [
      { id: "add", function: "TOPLA (A + B)", type: "action" },
      { id: "pick_max", function: "EN BÜYÜĞÜ SEÇ (MAX)", type: "logic" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: ["inbox_1", "inbox_2", "pick_max", "outbox"],
  },
  {
    id: 10,
    title: "Seviye 10: Üç Sayının Ortalaması (Master Level)",
    goal: "Gelen 3 sayıyı sırayla al, hepsini topla, 3'e böl ve sonucu çıktıya teslim et.",
    inputData: [6, 12, 18],
    expectedOutput: [12],
    initialBlocks: [
      { id: "div3", function: "3'e BÖL (/3)", type: "action" },
      { id: "sum3", function: "ÜÇÜNÜ TOPLA (A + B + C)", type: "action" },
      { id: "inbox_3", function: "GİRDİ AL (3. Sayı)", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
    ],
    correctOrder: ["inbox_1", "inbox_2", "inbox_3", "sum3", "div3", "outbox"],
  },
  {
    id: 11,
    title: "Seviye 11: Toplamın Karesi",
    goal: "İki sayıyı topla, sonucun karesini al ve çıktıya ver. (A+B)²",
    inputData: [2, 3],
    expectedOutput: [25],
    initialBlocks: [
      { id: "square", function: "KARESİNİ AL (A²)", type: "action" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "add", function: "TOPLA (A + B)", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: ["inbox_1", "inbox_2", "add", "square", "outbox"],
  },
  {
    id: 12,
    title: "Seviye 12: Farkın Mutlak Değeri",
    goal: "İki sayı arasındaki farkı bul, negatifse pozitife çevir. |A - B|",
    inputData: [9, 4],
    expectedOutput: [5],
    initialBlocks: [
      {
        id: "negate",
        function: "EĞER NEGATİFSE İŞARETİNİ DEĞİŞTİR",
        type: "action",
      },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "sub", function: "ÇIKAR (B - A)", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: ["inbox_1", "inbox_2", "sub", "negate", "outbox"],
  },
  {
    id: 13,
    title: "Seviye 13: Üçüncüden Toplamı Çıkar",
    goal: "İlk iki sayıyı topla. Üçüncü sayıdan bu toplamı çıkar ve sonucu ver. C - (A+B)",
    inputData: [3, 4, 10],
    expectedOutput: [3],
    initialBlocks: [
      { id: "sub", function: "ÇIKAR (B - A)", type: "action" },
      { id: "inbox_3", function: "GİRDİ AL (3. Sayı)", type: "io" },
      { id: "add", function: "TOPLA (A + B)", type: "action" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: ["inbox_1", "inbox_2", "add", "inbox_3", "sub", "outbox"],
  },
  {
    id: 14,
    title: "Seviye 14: Üç Sayı Arasından En Büyüğü Bul",
    goal: "Gelen üç sayıyı kıyasla, en büyük olanı çıktıya ver.",
    inputData: [5, 9, 3],
    expectedOutput: [9],
    initialBlocks: [
      { id: "pick_max_2", function: "EN BÜYÜĞÜ SEÇ (MAX)", type: "logic" },
      { id: "inbox_3", function: "GİRDİ AL (3. Sayı)", type: "io" },
      { id: "pick_max_1", function: "EN BÜYÜĞÜ SEÇ (MAX)", type: "logic" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: [
      "inbox_1",
      "inbox_2",
      "pick_max_1",
      "inbox_3",
      "pick_max_2",
      "outbox",
    ],
  },
  {
    id: 15,
    title: "Seviye 15: Karelerin Farkı",
    goal: "Her iki sayının karesini ayrı ayrı al, sonra ikincinin karesinden ilkinkini çıkar. B² - A²",
    inputData: [3, 5],
    expectedOutput: [16],
    initialBlocks: [
      { id: "sub", function: "ÇIKAR (B - A)", type: "action" },
      { id: "square_1", function: "KARESİNİ AL (A²)", type: "action" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "square_2", function: "KARESİNİ AL (A²)", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: [
      "inbox_1",
      "square_1",
      "inbox_2",
      "square_2",
      "sub",
      "outbox",
    ],
  },
  {
    id: 16,
    title: "Seviye 16: Sayıyı 9'a Böl",
    goal: "Gelen sayıyı arka arkaya iki kez 3'e böl (bu, 9'a bölmekle aynı sonucu verir).",
    inputData: [81],
    expectedOutput: [9],
    initialBlocks: [
      { id: "div3_2", function: "3'e BÖL (/3)", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "div3_1", function: "3'e BÖL (/3)", type: "action" },
      { id: "inbox", function: "GİRDİ AL", type: "io" },
    ],
    correctOrder: ["inbox", "div3_1", "div3_2", "outbox"],
  },
  {
    id: 17,
    title: "Seviye 17: Ortalamanın Karesi",
    goal: "Üç sayının ortalamasını hesapla, sonra ortalamanın karesini çıktıya ver.",
    inputData: [3, 3, 3],
    expectedOutput: [9],
    initialBlocks: [
      { id: "square", function: "KARESİNİ AL (A²)", type: "action" },
      { id: "inbox_3", function: "GİRDİ AL (3. Sayı)", type: "io" },
      { id: "div3", function: "3'e BÖL (/3)", type: "action" },
      { id: "sum3", function: "ÜÇÜNÜ TOPLA (A + B + C)", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
    ],
    correctOrder: [
      "inbox_1",
      "inbox_2",
      "inbox_3",
      "sum3",
      "div3",
      "square",
      "outbox",
    ],
  },
  {
    id: 18,
    title: "Seviye 18: Maksimumu Üçe Böl",
    goal: "İki sayıdan büyük olanını bul, sonra 3'e böl ve sonucu çıktıya ver.",
    inputData: [9, 18],
    expectedOutput: [6],
    initialBlocks: [
      { id: "div3", function: "3'e BÖL (/3)", type: "action" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "pick_max", function: "EN BÜYÜĞÜ SEÇ (MAX)", type: "logic" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: ["inbox_1", "inbox_2", "pick_max", "div3", "outbox"],
  },
  {
    id: 19,
    title: "Seviye 19: Negatif Kontrollü Toplam",
    goal: "İki sayıyı topla. Sonuç negatifse pozitife çevir, sonra çıktıya ver.",
    inputData: [-10, 3],
    expectedOutput: [7],
    initialBlocks: [
      {
        id: "negate",
        function: "EĞER NEGATİFSE İŞARETİNİ DEĞİŞTİR",
        type: "action",
      },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "add", function: "TOPLA (A + B)", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: ["inbox_1", "inbox_2", "add", "negate", "outbox"],
  },
  {
    id: 20,
    title: "Seviye 20: Dört Sayının Toplamı (Master Level)",
    goal: "Gelen dört sayıyı sırayla al ve hepsinin toplamını çıktıya ver.",
    inputData: [2, 4, 6, 8],
    expectedOutput: [20],
    initialBlocks: [
      { id: "add_3", function: "TOPLA (A + B)", type: "action" },
      { id: "inbox_4", function: "GİRDİ AL (4. Sayı)", type: "io" },
      { id: "inbox_2", function: "GİRDİ AL (2. Sayı)", type: "io" },
      { id: "add_2", function: "TOPLA (A + B)", type: "action" },
      { id: "outbox", function: "ÇIKTI VER", type: "io" },
      { id: "inbox_3", function: "GİRDİ AL (3. Sayı)", type: "io" },
      { id: "add_1", function: "TOPLA (A + B)", type: "action" },
      { id: "inbox_1", function: "GİRDİ AL (1. Sayı)", type: "io" },
    ],
    correctOrder: [
      "inbox_1",
      "inbox_2",
      "add_1",
      "inbox_3",
      "inbox_4",
      "add_2",
      "add_3",
      "outbox",
    ],
  },
];
